# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ac8b490b0db536181e65ed4ec217198"
application_url = "https://example.com"
embedded = true
name = "clearstack-audit"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_products,read_shopify_payments_accounts,read_shopify_payments_payouts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
