// Public privacy policy page — deliberately NOT behind authenticate.admin.
// This needs to be reachable by anyone (App Store reviewers, merchants
// evaluating the app before install) without a Shopify session, so it's
// plain HTML rather than the App Bridge (s-*) components used elsewhere,
// which depend on the App Bridge script only loaded inside the embedded
// admin iframe.
export default function Privacy() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Privacy Policy — ClearStack Audit</title>
        <style>{`
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #1a1a1a;
            max-width: 720px;
            margin: 0 auto;
            padding: 48px 24px 96px;
            line-height: 1.6;
          }
          h1 { font-size: 28px; margin-bottom: 4px; }
          h2 { font-size: 19px; margin-top: 40px; }
          p, li { font-size: 15px; }
          .updated { color: #616161; font-size: 14px; margin-top: 0; }
          ul { padding-left: 20px; }
          code { background: #f4f4f4; padding: 1px 5px; border-radius: 3px; font-size: 13px; }
        `}</style>
      </head>
      <body>
        <h1>Privacy Policy</h1>
        <p className="updated">Last updated: July 2026</p>

        <p>
          ClearStack Audit connects to your Shopify store and your QuickBooks Online
          company to compare the two and report discrepancies — missing orders,
          duplicate records, and payout mismatches — in plain language. This page
          explains what data the app touches, what it stores, and what it never does.
        </p>

        <h2>Read-only access</h2>
        <p>
          ClearStack Audit only ever reads data from Shopify and QuickBooks Online. It
          never creates, edits, or deletes anything in either system — no orders,
          products, or customers in Shopify, and no sales receipts, invoices, payments,
          deposits, or journal entries in QuickBooks. The QuickBooks connection is
          authorized with read-only access, and there is no code path in the app that
          performs a write operation against either platform.
        </p>

        <h2>What data we access</h2>
        <p>From your Shopify store, using the permissions granted at install:</p>
        <ul>
          <li>Orders — order number, date, financial status, and total amount</li>
          <li>Customer name on each order (used only to help match records; requires Shopify&apos;s protected customer data approval)</li>
          <li>Shopify Payments payouts — amount, fees, status, and issue date (only for stores using Shopify Payments)</li>
        </ul>
        <p>From your QuickBooks Online company, using the connection you authorize in the app&apos;s Settings page:</p>
        <ul>
          <li>Sales receipts, invoices, and payments — amounts, dates, reference numbers, and associated customer name</li>
          <li>Deposits — amounts, dates, and the receipts/payments they&apos;re composed of</li>
        </ul>

        <h2>What we store</h2>
        <p>
          The app stores two things, both scoped to your shop and neither containing
          order, payout, or customer transaction data:
        </p>
        <ul>
          <li>Your Shopify session token, standard for any Shopify app to authenticate API requests</li>
          <li>Your QuickBooks OAuth tokens (access and refresh token), needed to make QuickBooks API calls on your behalf between visits</li>
        </ul>
        <p>
          Order, payout, sales receipt, invoice, payment, and deposit data is never
          written to our database. Every report is generated by pulling current data
          from Shopify and QuickBooks at the moment you load the page, comparing it in
          memory, and returning the result — nothing about your individual transactions
          persists on our servers after the request completes.
        </p>

        <h2>Retention and deletion</h2>
        <p>
          Session and QuickBooks tokens are kept only while the app is installed and
          connected. Disconnecting QuickBooks from Settings immediately revokes and
          deletes those tokens. Uninstalling the app deletes your Shopify session, and
          any remaining shop data is fully deleted within 48 hours of uninstall, per
          Shopify&apos;s data protection requirements (<code>shop/redact</code>).
        </p>
        <p>
          Because the app never stores customer-level data, there is nothing
          customer-specific to retain or erase — customer data requests and erasure
          requests (<code>customers/data_request</code>, <code>customers/redact</code>)
          are acknowledged automatically since no such records exist here to act on.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this policy or how ClearStack Audit handles data can be sent
          to{" "}
          <a href="mailto:privacy@clearstack-audit.example">
            privacy@clearstack-audit.example
          </a>
          .
        </p>
      </body>
    </html>
  );
}
